DOC=electrolites.tex

all:
	pdflatex $(DOC)

clean:
	rm -f *.log *.aux *.toc *.lof *.lot *.out
	
#TeX=latex
#PNAME=electrolites
#DVIPS=dvips
#DVIPDF=dvipdfm
#DVI=$(PNAME).dvi
#PDF=$(PNAME).pdf
#TEXMAIN=$(PNAME).tex
#TEXFILES=$(TEXMAIN)
#
#pdf: toc.stamp $(DVI)
#	$(DVIPDF) $(DVI)
#
#ps: $(DVI)
#	$(DVIPS) $(DVI)
#
#toc.stamp:
#	$(TeX) $(TEXMAIN)
#	rm $(DVI)
#	touch toc.stamp
#
#$(DVI): $(TEXFILES)
#	$(TeX) $(TEXMAIN)
#
#clean:
#	rm -f *.log *.dvi *.aux *.toc *.lof *.lot *.out toc.stamp
